import psycopg2
conn = psycopg2.connect('dbname=cu_view_db user=cu_view_user password=SRY_NO_DOCKER_PASSWORD host=127.0.0.1 port=5432')
cur = conn.cursor()
cur.execute("SELECT recording_url FROM event_recordings LIMIT 5")
print("First 5 event_recordings:")
print(cur.fetchall())
cur.execute("SELECT recording_url FROM event_recordings WHERE recording_url NOT LIKE 'http%' LIMIT 5")
print("Event Recordings with NO http:")
print(cur.fetchall())
conn.close()
